name: Deployment Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  issues: write

jobs:
  parse-deployment-variable:
    runs-on: ubuntu-latest
    environment:
      name: Terraform Deployment Accounts
    outputs:
      matrix: ${{ steps.parse.outputs.matrix }}
    steps:
      - name: Parse Approved Deployments
        id: parse
        run: |
          echo "Parsing APPROVED_DEPLOYMENTS variable..."
          APPROVED="${{ vars.APPROVED_DEPLOYMENTS }}"
          echo "Approved Deployments: $APPROVED"

          # Generate matrix JSON
          MATRIX=$(echo "$APPROVED" | awk -F: '{ printf "{\"account\":\"%s\",\"region\":\"%s\"},", $1, $2 }' | sed 's/,$//')
          echo "matrix=[$MATRIX]" >> $GITHUB_OUTPUT

      - name: Debug Outputs
        run: |
          echo "Matrix JSON: ${{ steps.parse.outputs.matrix }}"

  deployment-matrix:
    needs: parse-deployment-variable
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.parse-deployment-variable.outputs.matrix) }}
      max-parallel: 1

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Echo Matrix Details
        run: |
          echo "Deploying to Account: ${{ matrix.account }}, Region: ${{ matrix.region }}"

      - name: Call Common Workflow
        uses: ./.github/workflows/common-workflow.yml
        with:
          account: ${{ matrix.account }}
          region: ${{ matrix.region }}