name: Deployment Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  issues: write

jobs:
  parse-deployment-variable:
    runs-on: ubuntu-latest
    environment:
      name: Terraform Deployment Accounts
    outputs:
      matrix: ${{ steps.parse.outputs.matrix }}
    steps:
      - name: Parse Approved Deployments
        id: parse
        run: |
          echo "Parsing APPROVED_DEPLOYMENTS variable..."
          APPROVED="${{ vars.APPROVED_DEPLOYMENTS }}"
          echo "Approved Deployments: $APPROVED"

          # Split and construct JSON matrix
          MATRIX=$(echo "$APPROVED" | tr ',' '\n' | awk -F: '{ printf "{\"account\":\"%s\",\"region\":\"%s\"},", $1, $2 }' | sed 's/,$//')
          echo "matrix=[$MATRIX]" >> $GITHUB_OUTPUT

      - name: Debug Outputs
        run: |
          echo "Matrix JSON: ${{ steps.parse.outputs.matrix }}"

  approval-job:
    needs: parse-deployment-variable
    runs-on: ubuntu-latest
    environment:
      name: qa
    steps:
      - name: Approval Required
        run: echo "Waiting for environment approval to proceed with deployment matrix."
        
  deployment-matrix:
    needs: [parse-deployment-variable, approval-job]
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.parse-deployment-variable.outputs.matrix) }}
      max-parallel: 1

    uses: ./.github/workflows/common-workflow.yml
    with:
      account: ${{ matrix.account }}
      region: ${{ matrix.region }}
    secrets: inherit