name: Deployment Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  issues: write

jobs:
  version-matrix:
    strategy:
      fail-fast: false
      matrix:
        account: [dev, prod, qa, stage]
        region: [us-east-2, us-west-2]
      max-parallel: 1

    uses: ./.github/workflows/common-workflow.yml
    with:
      account: ${{ matrix.account }}
      region: ${{ matrix.region }}
    secrets: inherit