name: Common Workflow

on:
  workflow_call:
    inputs:
      account:
        required: true
        type: string
      region:
        required: true
        type: string

permissions:
  issues: write

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Debug Outputs
        env:
          OUTPUT1: ${{ needs.check-approval.outputs.output1 }}
          OUTPUT2: ${{ needs.check-approval.outputs.output2 }}
          CHECK: ${{ needs.check-approval.outputs.check }}
        run: echo "$OUTPUT1 $OUTPUT2 $CHECK"

      - name: Plan TF
        run: |
          echo "Account: ${{ inputs.account }}"
          echo "Region: ${{ inputs.region }}"

      - name: Deploy Application
        run: |
          echo "Deploying to Account: ${{ inputs.account }} in Region: ${{ inputs.region }}"
