name: Common Workflow

on:
  workflow_call:
    inputs:
      account: # the variable you can use in place of a matrix
        required: true
        type: string
      region:
        required: true
        type: string

permissions:
  issues: write

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Plan TF
        run: |
          echo "Account: ${{ inputs.account }}"
          echo "Region: ${{ inputs.region }}"

      - name: Wait for manual approval
        uses: trstringer/manual-approval@v1.9.1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: cmartinezaraujo
          minimum-approvals: 1
          issue-title: "Deployment Approval for ${{ inputs.account }} in ${{ inputs.region }}"
          issue-body: |
            A deployment is pending approval for the following:
            - Account: ${{ inputs.account }}
            - Region: ${{ inputs.region }}

      - name: Deploy Application
        run: |
          echo "Deploying to Account: ${{ inputs.account }} in Region: ${{ inputs.region }}"