name: Common Workflow

on:
  workflow_call:
    inputs:
      account:
        required: true
        type: string
      region:
        required: true
        type: string

permissions:
  issues: write

jobs:
  check-approval:
    runs-on: ubuntu-latest
    environment:
      name: dev
    continue-on-error: true

    steps:
      - name: Check Approval for Deployment
        id: check
        run: |
          echo "Checking approval for Account: ${{ inputs.account }} and Region: ${{ inputs.region }}"
          if echo "${{ vars.APPROVED_DEPLOYMENTS }}" | grep -q "${{ inputs.account }}:${{ inputs.region }}"; then
            echo "approval_status=approved" >> $GITHUB_OUTPUT
          else
            echo "approval_status=denied" >> $GITHUB_OUTPUT
            exit 1
          fi

  terraform-deploy:
    runs-on: ubuntu-latest
    needs: check-approval
    if: ${{ needs.check-approval.outputs.approval_status == 'approved' }}
    environment:
      name: prod

    steps:
      - name: Plan TF
        run: |
          echo "Account: ${{ inputs.account }}"
          echo "Region: ${{ inputs.region }}"

      - name: Deploy Application
        run: |
          echo "Job status: ${{ needs.check-approval.outputs.approval_status == 'approved' }}"
          echo "Deploying to Account: ${{ inputs.account }} in Region: ${{ inputs.region }}"