name: Common Workflow

on:
  workflow_call:
    inputs:
      account:
        required: true
        type: string
      region:
        required: true
        type: string

permissions:
  issues: write

jobs:
  check-approval:
    runs-on: ubuntu-latest
    environment:
      name: dev

    steps:
      - name: Check Approval for Deployment
        run: |
          echo "Checking approval for Account: ${{ inputs.account }} and Region: ${{ inputs.region }}"
          if ! echo "${{ vars.APPROVED_DEPLOYMENTS }}" | grep -q "${{ inputs.account }}:${{ inputs.region }}"; then
            echo "Deployment to Account: ${{ inputs.account }} in Region: ${{ inputs.region }} is not approved."
            exit 1
          fi
          echo "Deployment approved for Account: ${{ inputs.account }} in Region: ${{ inputs.region }}"

  terraform-deploy:
    runs-on: ubuntu-latest
    needs: check-approval
    if: ${{ needs.check-approval.result == 'success' }} # Only run if check-approval succeeded

    steps:
      - name: Plan TF
        run: |
          echo "Account: ${{ inputs.account }}"
          echo "Region: ${{ inputs.region }}"

      - name: Deploy Application
        run: |
          echo "Deploying to Account: ${{ inputs.account }} in Region: ${{ inputs.region }}"