name: Common Workflow

on:
  workflow_call:
    inputs:
      account: # the variable you can use in place of a matrix
        required: true
        type: string
      region: 
        required: true
        type: string

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'job1 version ${{ inputs.account }}'

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo 'job2 version ${{ inputs.region }}'