name: Common Workflow

on:
  workflow_call:
    inputs:
      account:
        required: true
        type: string
      region:
        required: true
        type: string

permissions:
  issues: write

jobs:
  check-approval:
    runs-on: ubuntu-latest
    environment:
      name: dev
    continue-on-error: true
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}

    steps:
      - name: Check Approval for Deployment
        id: check
        run: |
          echo "Checking approval for Account: ${{ inputs.account }} and Region: ${{ inputs.region }}"
          if echo "${{ vars.APPROVED_DEPLOYMENTS }}" | grep -q "${{ inputs.account }}:${{ inputs.region }}"; then
            echo "approval_status=approved" >> $GITHUB_OUTPUT
          else
            echo "approval_status=denied" >> $GITHUB_OUTPUT
            exit 1

      - name: Step 1 Output
        id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"

      - name: Step 2 Output
        id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"

  terraform-deploy:
    runs-on: ubuntu-latest
    needs: check-approval

    steps:
      - name: Debug Outputs
        env:
          OUTPUT1: ${{ needs.check-approval.outputs.output1 }}
          OUTPUT2: ${{ needs.check-approval.outputs.output2 }}
        run: echo "$OUTPUT1 $OUTPUT2"

      - name: Plan TF
        run: |
          echo "Account: ${{ inputs.account }}"
          echo "Region: ${{ inputs.region }}"

      - name: Deploy Application
        run: |
          echo "Job status: ${{ needs.check-approval.outputs.approval_status == 'approved' }}"
          echo "Deploying to Account: ${{ inputs.account }} in Region: ${{ inputs.region }}"